from typing import Any, Optional, Set, Dict
from .. import util

RESERVED_WORDS: Set[str] = ...
LEGAL_CHARACTERS: Any = ...
ILLEGAL_INITIAL_CHARACTERS: Any = ...
BIND_PARAMS: Any = ...
BIND_PARAMS_ESC: Any = ...
BIND_TEMPLATES: Dict[str, str] = ...
OPERATORS: Any = ...
FUNCTIONS: Any = ...
EXTRACT_MAP: Dict[str, str] = ...
COMPOUND_KEYWORDS: Any = ...

class Compiled(object):
    execution_options: Any = ...
    dialect: Any = ...
    bind: Any = ...
    preparer: Any = ...
    statement: Any = ...
    can_execute: Any = ...
    string: Any = ...
    def __init__(self, dialect, statement, bind: Optional[Any] = ..., schema_translate_map: Optional[Any] = ...,
                 compile_kwargs: Any = ...) -> None: ...
    def compile(self): ...
    @property
    def sql_compiler(self): ...
    def process(self, obj, **kwargs): ...
    def construct_params(self, params: Optional[Any] = ...): ...
    @property
    def params(self): ...
    def execute(self, *multiparams, **params): ...
    def scalar(self, *multiparams, **params): ...

class TypeCompiler(metaclass=util.EnsureKWArgType):
    ensure_kwarg: str = ...
    dialect: Any = ...
    def __init__(self, dialect) -> None: ...
    def process(self, type_, **kw): ...

class SQLCompiler(Compiled):
    extract_map: Any = ...
    compound_keywords: Any = ...
    isdelete: bool = ...
    isinsert: bool = ...
    isupdate: bool = ...
    isplaintext: bool = ...
    returning: Any = ...
    returning_precedes_values: bool = ...
    render_table_with_column_in_update_from: bool = ...
    ansi_bind_rules: bool = ...
    insert_prefetch: Any = ...
    update_prefetch: Any = ...
    column_keys: Any = ...
    inline: Any = ...
    binds: Any = ...
    bind_names: Any = ...
    stack: Any = ...
    positional: Any = ...
    positiontup: Any = ...
    bindtemplate: Any = ...
    ctes: Any = ...
    label_length: Any = ...
    anon_map: Any = ...
    truncated_names: Any = ...
    def __init__(self, dialect, statement, column_keys: Optional[Any] = ..., inline: bool = ..., **kwargs) -> None: ...
    @property
    def prefetch(self): ...
    def is_subquery(self): ...
    @property
    def sql_compiler(self): ...
    def construct_params(self, params: Optional[Any] = ..., _group_number: Optional[Any] = ..., _check: bool = ...): ...
    @property
    def params(self): ...
    def default_from(self): ...
    def visit_grouping(self, grouping, asfrom: bool = ..., **kwargs): ...
    def visit_label_reference(self, element, within_columns_clause: bool = ..., **kwargs): ...
    def visit_textual_label_reference(self, element, within_columns_clause: bool = ..., **kwargs): ...
    def visit_label(self, label, add_to_result_map: Optional[Any] = ..., within_label_clause: bool = ...,
                    within_columns_clause: bool = ..., render_label_as_label: Optional[Any] = ..., **kw): ...
    def visit_column(self, column, add_to_result_map: Optional[Any] = ..., include_table: bool = ..., **kwargs): ...
    def escape_literal_column(self, text): ...
    def visit_fromclause(self, fromclause, **kwargs): ...
    def visit_index(self, index, **kwargs): ...
    def visit_typeclause(self, typeclause, **kw): ...
    def post_process_text(self, text): ...
    def visit_textclause(self, textclause, **kw): ...
    def visit_text_as_from(self, taf, compound_index: Optional[Any] = ..., asfrom: bool = ...,
                           parens: bool = ..., **kw): ...
    def visit_null(self, expr, **kw): ...
    def visit_true(self, expr, **kw): ...
    def visit_false(self, expr, **kw): ...
    def visit_clauselist(self, clauselist, **kw): ...
    def visit_case(self, clause, **kwargs): ...
    def visit_type_coerce(self, type_coerce, **kw): ...
    def visit_cast(self, cast, **kwargs): ...
    def visit_over(self, over, **kwargs): ...
    def visit_withingroup(self, withingroup, **kwargs): ...
    def visit_funcfilter(self, funcfilter, **kwargs): ...
    def visit_extract(self, extract, **kwargs): ...
    def visit_function(self, func, add_to_result_map: Optional[Any] = ..., **kwargs): ...
    def visit_next_value_func(self, next_value, **kw): ...
    def visit_sequence(self, sequence): ...
    def function_argspec(self, func, **kwargs): ...
    def visit_compound_select(self, cs, asfrom: bool = ..., parens: bool = ...,
                              compound_index: int = ..., **kwargs): ...
    def visit_unary(self, unary, **kw): ...
    def visit_istrue_unary_operator(self, element, operator, **kw): ...
    def visit_isfalse_unary_operator(self, element, operator, **kw): ...
    def visit_notmatch_op_binary(self, binary, operator, **kw): ...
    def visit_binary(self, binary, override_operator: Optional[Any] = ...,
                     eager_grouping: bool = ..., **kw): ...
    def visit_custom_op_binary(self, element, operator, **kw): ...
    def visit_custom_op_unary_operator(self, element, operator, **kw): ...
    def visit_custom_op_unary_modifier(self, element, operator, **kw): ...
    def visit_contains_op_binary(self, binary, operator, **kw): ...
    def visit_notcontains_op_binary(self, binary, operator, **kw): ...
    def visit_startswith_op_binary(self, binary, operator, **kw): ...
    def visit_notstartswith_op_binary(self, binary, operator, **kw): ...
    def visit_endswith_op_binary(self, binary, operator, **kw): ...
    def visit_notendswith_op_binary(self, binary, operator, **kw): ...
    def visit_like_op_binary(self, binary, operator, **kw): ...
    def visit_notlike_op_binary(self, binary, operator, **kw): ...
    def visit_ilike_op_binary(self, binary, operator, **kw): ...
    def visit_notilike_op_binary(self, binary, operator, **kw): ...
    def visit_between_op_binary(self, binary, operator, **kw): ...
    def visit_notbetween_op_binary(self, binary, operator, **kw): ...
    def visit_bindparam(self, bindparam, within_columns_clause: bool = ..., literal_binds: bool = ...,
                        skip_bind_expression: bool = ..., **kwargs): ...
    def render_literal_bindparam(self, bindparam, **kw): ...
    def render_literal_value(self, value, type_): ...
    def bindparam_string(self, name, positional_names: Optional[Any] = ..., **kw): ...
    execution_options: Any = ...
    ctes_recursive: bool = ...
    def visit_cte(self, cte, asfrom: bool = ..., ashint: bool = ...,
                  fromhints: Optional[Any] = ..., **kwargs): ...
    def visit_alias(self, alias, asfrom: bool = ..., ashint: bool = ..., iscrud: bool = ...,
                    fromhints: Optional[Any] = ..., **kwargs): ...
    def visit_lateral(self, lateral, **kw): ...
    def visit_tablesample(self, tablesample, asfrom: bool = ..., **kw): ...
    def get_render_as_alias_suffix(self, alias_name_text): ...
    def format_from_hint_text(self, sqltext, table, hint, iscrud): ...
    def get_select_hint_text(self, byfroms): ...
    def get_from_hint_text(self, table, text): ...
    def get_crud_hint_text(self, table, text): ...
    def get_statement_hint_text(self, hint_texts): ...
    def visit_select(self, select, asfrom: bool = ..., parens: bool = ..., fromhints: Optional[Any] = ...,
                     compound_index: int = ..., nested_join_translation: bool = ...,
                     select_wraps_for: Optional[Any] = ..., lateral: bool = ..., **kwargs): ...
    def get_cte_preamble(self, recursive): ...
    def get_select_precolumns(self, select, **kw): ...
    def order_by_clause(self, select, **kw): ...
    def for_update_clause(self, select, **kw): ...
    def returning_clause(self, stmt, returning_cols): ...
    def limit_clause(self, select, **kw): ...
    def visit_table(self, table, asfrom: bool = ..., iscrud: bool = ..., ashint: bool = ...,
                    fromhints: Optional[Any] = ..., use_schema: bool = ..., **kwargs): ...
    def visit_join(self, join, asfrom: bool = ..., **kwargs): ...
    def visit_insert(self, insert_stmt, asfrom: bool = ..., **kw): ...
    def update_limit_clause(self, update_stmt): ...
    def update_tables_clause(self, update_stmt, from_table, extra_froms, **kw): ...
    def update_from_clause(self, update_stmt, from_table, extra_froms, from_hints, **kw): ...
    def visit_update(self, update_stmt, asfrom: bool = ..., **kw): ...
    def visit_delete(self, delete_stmt, asfrom: bool = ..., **kw): ...
    def visit_savepoint(self, savepoint_stmt): ...
    def visit_rollback_to_savepoint(self, savepoint_stmt): ...
    def visit_release_savepoint(self, savepoint_stmt): ...

class StrSQLCompiler(SQLCompiler):
    def visit_getitem_binary(self, binary, operator, **kw): ...
    def visit_json_getitem_op_binary(self, binary, operator, **kw): ...
    def visit_json_path_getitem_op_binary(self, binary, operator, **kw): ...
    def returning_clause(self, stmt, returning_cols): ...

class DDLCompiler(Compiled):
    @property
    def sql_compiler(self): ...
    @property
    def type_compiler(self): ...
    def construct_params(self, params: Optional[Any] = ...): ...
    def visit_ddl(self, ddl, **kwargs): ...
    def visit_create_schema(self, create): ...
    def visit_drop_schema(self, drop): ...
    def visit_create_table(self, create): ...
    def visit_create_column(self, create, first_pk: bool = ...): ...
    def create_table_constraints(self, table, _include_foreign_key_constraints: Optional[Any] = ...): ...
    def visit_drop_table(self, drop): ...
    def visit_drop_view(self, drop): ...
    def visit_create_index(self, create, include_schema: bool = ..., include_table_schema: bool = ...): ...
    def visit_drop_index(self, drop): ...
    def visit_add_constraint(self, create): ...
    def visit_create_sequence(self, create): ...
    def visit_drop_sequence(self, drop): ...
    def visit_drop_constraint(self, drop): ...
    def get_column_specification(self, column, **kwargs): ...
    def create_table_suffix(self, table): ...
    def post_create_table(self, table): ...
    def get_column_default_string(self, column): ...
    def visit_check_constraint(self, constraint): ...
    def visit_column_check_constraint(self, constraint): ...
    def visit_primary_key_constraint(self, constraint): ...
    def visit_foreign_key_constraint(self, constraint): ...
    def define_constraint_remote_table(self, constraint, table, preparer): ...
    def visit_unique_constraint(self, constraint): ...
    def define_constraint_cascades(self, constraint): ...
    def define_constraint_deferrability(self, constraint): ...
    def define_constraint_match(self, constraint): ...

class GenericTypeCompiler(TypeCompiler):
    def visit_FLOAT(self, type_, **kw): ...
    def visit_REAL(self, type_, **kw): ...
    def visit_NUMERIC(self, type_, **kw): ...
    def visit_DECIMAL(self, type_, **kw): ...
    def visit_INTEGER(self, type_, **kw): ...
    def visit_SMALLINT(self, type_, **kw): ...
    def visit_BIGINT(self, type_, **kw): ...
    def visit_TIMESTAMP(self, type_, **kw): ...
    def visit_DATETIME(self, type_, **kw): ...
    def visit_DATE(self, type_, **kw): ...
    def visit_TIME(self, type_, **kw): ...
    def visit_CLOB(self, type_, **kw): ...
    def visit_NCLOB(self, type_, **kw): ...
    def visit_CHAR(self, type_, **kw): ...
    def visit_NCHAR(self, type_, **kw): ...
    def visit_VARCHAR(self, type_, **kw): ...
    def visit_NVARCHAR(self, type_, **kw): ...
    def visit_TEXT(self, type_, **kw): ...
    def visit_BLOB(self, type_, **kw): ...
    def visit_BINARY(self, type_, **kw): ...
    def visit_VARBINARY(self, type_, **kw): ...
    def visit_BOOLEAN(self, type_, **kw): ...
    def visit_large_binary(self, type_, **kw): ...
    def visit_boolean(self, type_, **kw): ...
    def visit_time(self, type_, **kw): ...
    def visit_datetime(self, type_, **kw): ...
    def visit_date(self, type_, **kw): ...
    def visit_big_integer(self, type_, **kw): ...
    def visit_small_integer(self, type_, **kw): ...
    def visit_integer(self, type_, **kw): ...
    def visit_real(self, type_, **kw): ...
    def visit_float(self, type_, **kw): ...
    def visit_numeric(self, type_, **kw): ...
    def visit_string(self, type_, **kw): ...
    def visit_unicode(self, type_, **kw): ...
    def visit_text(self, type_, **kw): ...
    def visit_unicode_text(self, type_, **kw): ...
    def visit_enum(self, type_, **kw): ...
    def visit_null(self, type_, **kw): ...
    def visit_type_decorator(self, type_, **kw): ...
    def visit_user_defined(self, type_, **kw): ...

class StrSQLTypeCompiler(GenericTypeCompiler):
    def __getattr__(self, key): ...

class IdentifierPreparer(object):
    reserved_words: Any = ...
    legal_characters: Any = ...
    illegal_initial_characters: Any = ...
    schema_for_object: Any = ...
    dialect: Any = ...
    initial_quote: Any = ...
    final_quote: Any = ...
    escape_quote: Any = ...
    escape_to_quote: Any = ...
    omit_schema: Any = ...
    def __init__(self, dialect, initial_quote: str = ..., final_quote: Optional[Any] = ...,
                 escape_quote: str = ..., omit_schema: bool = ...) -> None: ...
    def quote_identifier(self, value): ...
    def quote_schema(self, schema, force: Optional[Any] = ...): ...
    def quote(self, ident, force: Optional[Any] = ...): ...
    def format_sequence(self, sequence, use_schema: bool = ...): ...
    def format_label(self, label, name: Optional[Any] = ...): ...
    def format_alias(self, alias, name: Optional[Any] = ...): ...
    def format_savepoint(self, savepoint, name: Optional[Any] = ...): ...
    def format_constraint(self, constraint): ...
    def format_table(self, table, use_schema: bool = ..., name: Optional[Any] = ...): ...
    def format_schema(self, name, quote: Optional[Any] = ...): ...
    def format_column(self, column, use_table: bool = ..., name: Optional[Any] = ...,
                      table_name: Optional[str] = ...): ...
    def format_table_seq(self, table, use_schema: bool = ...): ...
    def unformat_identifiers(self, identifiers): ...
