from typing import Any

class ConventionDict(object):
    const: Any = ...
    table: Any = ...
    convention: Any = ...
    def __init__(self, const, table, convention) -> None: ...
    def __getitem__(self, key): ...
