from typing import Any, Optional

class scoped_session(object):
    session_factory: Any = ...
    registry: Any = ...
    def __init__(self, session_factory, scopefunc: Optional[Any] = ...) -> None: ...
    def __call__(self, **kw): ...
    def remove(self): ...
    def configure(self, **kwargs): ...
    def query_property(self, query_cls: Optional[Any] = ...): ...
